name: Build
on:
  push:
    paths:
      - '**.4dm'
  pull_request:
    paths:
      - '**.4dm'
  workflow_dispatch:

jobs:
  build:
    name: "Build on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check out dependencies
      uses: actions/checkout@v3
      with:
        repository: 4d/4D-Progress
        path: Components/4D-Progress.4dbase
    - name: Build
      uses: 4d/build4d-action@main
