name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '.github/cla/signatures.json'
          path-to-document: 'https://github.com/${GITHUB_REPOSITORY}/blob/main/.github/cla/4DCLA.md'
          # branch should not be protected
          branch: 'main'
          allowlist: 4DBuildMgr,DamienFuzeau,JarosMachacek,Mohammed-Ouakani,Roland-Lannuzel,Souhail-Elmouhtadi,ThomasMaul,abdelkrim-bouhoute,ahmed-rajouani-alaoui,amine-maqrot,anass-talii,arnaud4d,brahim-boukobba,david-azancot,delahaye-4D,djotandjigora,e-marchand,emmanuel-craeymeersch,fabrice-mainguene,franck-louvigne,francois-marchal,guillaume-kotulski,halima-laghroubi,htemanni92,jacques-quidu,jean-laguerre,laurent-esnault,lribardi,majda-elmaazouzi,mathieu-ferry,michel-blaise,mickael-cerisier,migad-negib,moussa-bellahcene,ms-landrieu,nicolas-brachfogel,nobuteshima,noreddine-margoum,omar-hcine,omar-lakrari,ossama-mourini,patrick-poly,pfhuillet,quentinmarciset,sclairet,vdelachaux,vincent-laluque,vtalbot4D,walid-chekkouri,yannicktrinh,zineb-aslioui