name: Release
on: 
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      GITHUB_RELEASE_TAG: "${{ github.event.release.tag_name }}"
    permissions:
      contents: write # for asset upload
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
      - name: download sdks & generator
        run: |
           mkdir -p ./Resources/sdk
           if [[ "$GITHUB_RELEASE_TAG" == *-fat ]]; then
             echo "Download SDKs"
             curl -sL https://github.com/4d/ios-sdk/releases/latest/download/ios.zip -o ./Resources/sdk/ios.zip
             curl -sL https://github.com/4d/android-sdk/releases/latest/download/android.zip -o ./Resources/sdk/android.zip
           fi 
           echo "Download Android Project Generator"
           curl -sL https://github.com/4d/android-ProjectGenerator/releases/latest/download/androidprojectgenerator.jar -o ./Resources/scripts/androidprojectgenerator.jar
      - name: Check out 4D-Progress
        uses: actions/checkout@v4
        with:
          repository: 4d/4D-Progress
          path: Components/4D-Progress.4dbase
      - name: BuildAndPackage
        uses: 4d/build4d-action@main
        with:
          actions: "build,pack,archive"
      - name: Upload
        run: |
          gh release upload ${{github.event.release.tag_name}} "build/4D-Mobile-App.zip"
